# Site info
site_name: Codex
site_url: https://sh3ll.co
site_author: SH3LL
site_description: >-
  A-Z Cybersecurity, Networking, Research, and Resources.

# Repo
repo_name: SH3LLco/Codex
repo_url: https://github.com/SH3LLco/Codex
edit_uri: edit/main/docs/

# Copyright
copyright: >
  Copyright &copy; 2025 SH3LL -

  <a href="#__consent">[ Cookie Settings ]</a>

# Config
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.tags
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.prune
    - navigation.instant.preview
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - search.index
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: indigo
  font:
    text: Roboto Medium
    code: Roboto Mono
  favicon: assets/images/favicon.png
  icon:
    logo: assets/logo

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - social:
      cards_layout: default/accent
      cards_layout_options:
        background_color: "#1E202BD3"
        background_image: docs/assets/card.png
        logo: docs/assets/SH3LL.png
  - tags
  - typeset
  - redirects
  - backlinks_section:
      ignore_links_from:
        - tags.md
      ignore_links_to:
        - index.md
        - tags.md
  - exclude:
      glob:
        - ".obsidian/*"
        - "Private/*"
        - "Workshop/*"
        - ".DS_Store"
  - mermaid2:
        arguments:
          securityLevel: 'loose'
  - privacy
  - glightbox
  - panzoom:
      full_screen: true
      always_show_hint: true
      key: "shift"
  - meta
  - optimize:
      cache: false

# Extra
extra:
  analytics:
    provider: google
    property: G-Y7WM770MNT
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SH3LLco
    - icon: fontawesome/brands/discord
      link: https://discord.gg/infophreak
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gino-f-b179341ba/
    - icon: fontawesome/solid/blog
      link: https://infophreak.com/author/sh3ll/
  search:
    indexing: full
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

# Extensions
markdown_extensions:
  - tables
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

extra_css:
  - stylesheets/extra.css

# Navigation
nav:
  - About:
    - about/index.md
    - License: about/license.md
    - Disclaimer: about/disclaimer.md
    - Sponsorship: about/sponsor.md
    - Tips & Donations: about/donate.md
    - Contact: about/contact.md
    - Report an issue: about/report.md
    - Community: about/community.md
  - Offensive Security: 
    - offense/index.md
  - Defensive Security: 
    - defense/index.md
  - Core Competencies: 
    - core/index.md
    - Networking: core/networking/index.md
  - Systems & Internals: 
    - sysint/index.md
  - Research: 
    - research/index.md
  - Resources & References: 
    - resource-ref/index.md
  - Tags: tags.md